### ISSUE TITLE
Generate Pipeline script in the workspace for every build

### ISSUE THREAD

**Issue by SangaviJayagopi** [mathworks/jenkins-matlab-plugin#108]
Is it possible to generate pipeline script in the workspace?

In case of a pipeline project, Jenkins creates workspace folder for every build. It would be nice to see the pipeline script that runs in the build. However, there are pipeline steps generated for the build. Could we use it to leverage?

Seeing this similar other CI services, where we have the YAML file for every build.

**Comment by nbhoski** [comment]
I dont think i have understood it correctly but  do you want to create a custom workspace during the build? if so then i guess you could do so by using customWorkspace  property of node{} block .

**Comment by SangaviJayagopi** [comment]
When we run build on Jenkins using a pipeline script, If there is a way, to generate the same pipeline script in the workspace at the end of build? It is to keep track of build results with the respective pipeline script.

**Comment by acampbel** [comment]
> When we run build on Jenkins using a pipeline script, If there is a way, to generate the same pipeline script in the workspace at the end of build? It is to keep track of build results with the respective pipeline script.

The equivalent to a yaml file is the Jenkinsfile:
https://www.jenkins.io/doc/book/pipeline/jenkinsfile/

**Comment by nbhoski** [comment]
I agree its a handy behaviour of few other CI platforms that you mentioned but i think this type of feature is very CI platform-specific. I am not aware of Jenkins feature which would rewrite the entire script at the end of every build. This may not be in the scope of plugin development considerations.

**Comment by acampbel** [comment]
I think what you are asking for is handled by the Jenkinsfile. No need to add a specific feature around this. Please reopen if I missed something

**Comment by SangaviJayagopi** [comment]
I agree it is a CI platform-specific feature. Not specific to our plugin.
