### ISSUE TITLE
In a Matrix project, if one version of MATLAB is not available, build fails incase run from Mac but build does not fail incase run from Windows

### ISSUE THREAD

**Issue by SangaviJayagopi** [mathworks/jenkins-matlab-plugin#110]
1. Create a Multi-Config project on Jenkins on Mac and Windows
2. Add user-defined axis and versions
3. Add versions that is not in the system
4.The build fails in Mac but not in Windows.

Please refer to logs here:

In case of Mac,

Started by user Sangavi Jayagopi
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] node
Running on Jenkins in /Users/sjayagop/.jenkins/workspace/test_pipeline_dsl
[Pipeline] {
[Pipeline] stage
[Pipeline] { (BuildAndTest)
[Pipeline] parallel
[Pipeline] { (Branch: Matrix - VERSION = 'R2019a')
[Pipeline] { (Branch: Matrix - VERSION = 'R2019b')
[Pipeline] stage
[Pipeline] { (Matrix - VERSION = 'R2019a')
[Pipeline] stage
[Pipeline] { (Matrix - VERSION = 'R2019b')
[Pipeline] withEnv
[Pipeline] {
[Pipeline] withEnv
[Pipeline] {
[Pipeline] node
[Pipeline] node
Running on Jenkins in /Users/sjayagop/.jenkins/workspace/test_pipeline_dsl@2
[Pipeline] {
[Pipeline] withEnv
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Run MATLAB Command)
[Pipeline] runMATLABCommand
[test_pipeline_dsl@2] $ /var/folders/bc/l10_249126g1thr9hhsv2wj4000fnq/T//13f5c350-30e5-4692-9f08-209620ee1a63/run_matlab_command.sh pwd

ans =

    '/Users/sjayagop/.jenkins/workspace/test_pipeline_dsl@2'

[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
Running on Jenkins in /Users/sjayagop/.jenkins/workspace/test_pipeline_dsl@2
[Pipeline] // node
[Pipeline] {
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] withEnv
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Run MATLAB Command)
[Pipeline] runMATLABCommand
[test_pipeline_dsl@2] $ /var/folders/bc/l10_249126g1thr9hhsv2wj4000fnq/T//c3b065c8-0265-496f-8271-bf61381e11be/run_matlab_command.sh pwd
'matlab' command not found. Please make sure MATLAB_ROOT/bin is on
the system path, where MATLAB_ROOT is the full path to your MATLAB
installation directory.
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // parallel
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: FAILURE

In case of windows:

Started by user sjayagop
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] node
Running on Jenkins in C:\Program Files (x86)\Jenkins\workspace\test_pipeline_dsl
[Pipeline] {
[Pipeline] stage
[Pipeline] { (BuildAndTest)
[Pipeline] parallel
[Pipeline] { (Branch: Matrix - VERSION = 'R2018b')
[Pipeline] { (Branch: Matrix - VERSION = 'R2020a')
[Pipeline] stage
[Pipeline] { (Matrix - VERSION = 'R2018b')
[Pipeline] stage
[Pipeline] { (Matrix - VERSION = 'R2020a')
[Pipeline] withEnv
[Pipeline] {
[Pipeline] withEnv
[Pipeline] {
[Pipeline] node
Running on Jenkins in C:\Program Files (x86)\Jenkins\workspace\test_pipeline_dsl@2
[Pipeline] node
[Pipeline] {
[Pipeline] withEnv
[Pipeline] {
[Pipeline] stage
[Pipeline] { (scm checkout)
[Pipeline] git
Warning: CredentialId "5f59e6e8-8b32-4c30-8461-bd17c2ac4fac" could not be found.
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/SangaviJayagopi/matlab-plugin-bash-repo # timeout=10
Fetching upstream changes from https://github.com/SangaviJayagopi/matlab-plugin-bash-repo
 > git --version # timeout=10
 > git fetch --tags --force --progress -- https://github.com/SangaviJayagopi/matlab-plugin-bash-repo +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse "refs/remotes/origin/master^{commit}" # timeout=10
 > git rev-parse "refs/remotes/origin/origin/master^{commit}" # timeout=10
Checking out Revision af10ff2a123a66b3666212537956239eff7f8b0e (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f af10ff2a123a66b3666212537956239eff7f8b0e # timeout=10
 > git branch -a -v --no-abbrev # timeout=10
 > git branch -D master # timeout=10
 > git checkout -b master af10ff2a123a66b3666212537956239eff7f8b0e # timeout=10
Commit message: "Create rightTriTest.m"
 > git rev-list --no-walk af10ff2a123a66b3666212537956239eff7f8b0e # timeout=10
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Run MATLAB commands)
[Pipeline] runMATLABCommand
[test_pipeline_dsl@2] $ cmd.exe /C C:\Users\sjayagop\AppData\Local\Temp\\40a822de-e508-4e74-9440-03e32c8c5fe7\run_matlab_command.bat "ver"
-----------------------------------------------------------------------------------------------------
MATLAB Version: 9.8.0.1323502 (R2020a)
MATLAB License Number: 40447121
Operating System: Microsoft Windows 10 Enterprise Version 10.0 (Build 18362)
Java Version: Java 1.8.0_202-b08 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
-----------------------------------------------------------------------------------------------------
MATLAB                                                Version 9.8         (R2020a)
Simulink                                              Version 10.1        (R2020a)
LTE Toolbox                                           Version 3.3         (R2020a)
MATLAB Coder                                          Version 5.0         (R2020a)
MATLAB Compiler                                       Version 8.0         (R2020a)
MATLAB Compiler SDK                                   Version 6.8         (R2020a)
MATLAB Report Generator                               Version 5.8         (R2020a)
Mapping Toolbox                                       Version 4.10        (R2020a)
Signal Processing Toolbox                             Version 8.4         (R2020a)
Simulink 3D Animation                                 Version 9.0         (R2020a)
Simulink Check                                        Version 4.5         (R2020a)
Simulink Code Inspector                               Version 3.6         (R2020a)
Simulink Coder                                        Version 9.3         (R2020a)
Simulink Compiler                                     Version 1.0         (R2020a)
Simulink Control Design                               Version 5.5         (R2020a)
Simulink Coverage                                     Version 5.0         (R2020a)
Simulink Design Optimization                          Version 3.8         (R2020a)
Simulink Design Verifier                              Version 4.3         (R2020a)
Simulink Desktop Real-Time                            Version 5.10        (R2020a)
Simulink PLC Coder                                    Version 3.2         (R2020a)
Simulink Real-Time                                    Version 6.12        (R2020a)
Simulink Report Generator                             Version 5.8         (R2020a)
Simulink Requirements                                 Version 1.5         (R2020a)
Simulink Test                                         Version 3.2         (R2020a)
[Pipeline] runMATLABCommand
[test_pipeline_dsl@2] $ cmd.exe /C C:\Users\sjayagop\AppData\Local\Temp\\e4774d86-752a-4f79-a434-8ddffdd224ef\run_matlab_command.bat "pwd"

ans =

    'C:\Program Files (x86)\Jenkins\workspace\test_pipeline_dsl@2'

[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
Running on Jenkins in C:\Program Files (x86)\Jenkins\workspace\test_pipeline_dsl@2
[Pipeline] // node
[Pipeline] {
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] withEnv
[Pipeline] {
[Pipeline] stage
[Pipeline] { (scm checkout)
[Pipeline] git
Warning: CredentialId "5f59e6e8-8b32-4c30-8461-bd17c2ac4fac" could not be found.
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/SangaviJayagopi/matlab-plugin-bash-repo # timeout=10
Fetching upstream changes from https://github.com/SangaviJayagopi/matlab-plugin-bash-repo
 > git --version # timeout=10
 > git fetch --tags --force --progress -- https://github.com/SangaviJayagopi/matlab-plugin-bash-repo +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse "refs/remotes/origin/master^{commit}" # timeout=10
 > git rev-parse "refs/remotes/origin/origin/master^{commit}" # timeout=10
Checking out Revision af10ff2a123a66b3666212537956239eff7f8b0e (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f af10ff2a123a66b3666212537956239eff7f8b0e # timeout=10
 > git branch -a -v --no-abbrev # timeout=10
 > git branch -D master # timeout=10
 > git checkout -b master af10ff2a123a66b3666212537956239eff7f8b0e # timeout=10
Commit message: "Create rightTriTest.m"
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Run MATLAB commands)
[Pipeline] runMATLABCommand
[test_pipeline_dsl@2] $ cmd.exe /C C:\Users\sjayagop\AppData\Local\Temp\\6fd318f1-204a-4a75-b23b-25b41bd87c36\run_matlab_command.bat "ver"
-----------------------------------------------------------------------------------------------------
MATLAB Version: 9.8.0.1323502 (R2020a)
MATLAB License Number: 40447121
Operating System: Microsoft Windows 10 Enterprise Version 10.0 (Build 18362)
Java Version: Java 1.8.0_202-b08 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
-----------------------------------------------------------------------------------------------------
MATLAB                                                Version 9.8         (R2020a)
Simulink                                              Version 10.1        (R2020a)
LTE Toolbox                                           Version 3.3         (R2020a)
MATLAB Coder                                          Version 5.0         (R2020a)
MATLAB Compiler                                       Version 8.0         (R2020a)
MATLAB Compiler SDK                                   Version 6.8         (R2020a)
MATLAB Report Generator                               Version 5.8         (R2020a)
Mapping Toolbox                                       Version 4.10        (R2020a)
Signal Processing Toolbox                             Version 8.4         (R2020a)
Simulink 3D Animation                                 Version 9.0         (R2020a)
Simulink Check                                        Version 4.5         (R2020a)
Simulink Code Inspector                               Version 3.6         (R2020a)
Simulink Coder                                        Version 9.3         (R2020a)
Simulink Compiler                                     Version 1.0         (R2020a)
Simulink Control Design                               Version 5.5         (R2020a)
Simulink Coverage                                     Version 5.0         (R2020a)
Simulink Design Optimization                          Version 3.8         (R2020a)
Simulink Design Verifier                              Version 4.3         (R2020a)
Simulink Desktop Real-Time                            Version 5.10        (R2020a)
Simulink PLC Coder                                    Version 3.2         (R2020a)
Simulink Real-Time                                    Version 6.12        (R2020a)
Simulink Report Generator                             Version 5.8         (R2020a)
Simulink Requirements                                 Version 1.5         (R2020a)
Simulink Test                                         Version 3.2         (R2020a)
[Pipeline] runMATLABCommand
[test_pipeline_dsl@2] $ cmd.exe /C C:\Users\sjayagop\AppData\Local\Temp\\84455bee-8d4d-442b-bbd3-475d37aa041f\run_matlab_command.bat "pwd"

ans =

    'C:\Program Files (x86)\Jenkins\workspace\test_pipeline_dsl@2'

[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // parallel
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS

**Comment by nbhoski** [comment]
May be you have R2020a MATLAB already in the system PATH . Could you check if that is the case please remove all MATLAB from system path and try again.

**Comment by SangaviJayagopi** [comment]
I removed all SYSTEM PATH variables of MATLAB in Windows and ran the build, the build seems to work as expected.That is, the build fails if a MATLAB Instance in not available locally.
