### ISSUE TITLE
java.io.tmpdir returns \ at the end in Windows system

### ISSUE THREAD

**Issue by wyoshio** [mathworks/jenkins-matlab-plugin#113]
In my Windows 10, generated folder path contains two '\\' marks after the temp folder like below:

[hello] $ cmd.exe /C C:\Users\myusername\AppData\Local\Temp\\\\651b1a37-8a22-4651-8a41-4019acfe5fbf\run_matlab_command.bat "exit(runMatlabTests())"

**Comment by nbhoski** [comment]
can you please elaborate this issue. I dont think i have understood this well.

**Comment by wyoshio** [comment]
I got the following error, when I run an example:
![image](https://user-images.githubusercontent.com/46220668/87490501-c7e4de00-c680-11ea-901d-b603c8bf92cd.png)
This shows 'name doesn't exist or it isn't a directory' in Japanese. I guess that 2 backslashes in a row after 'Temp' folder would cause this error.

Then as far as I searched, I guess these 2 backslashes come from: 
(1) The backslash added in a source code 'MatlabBuild.java': 
            matlabLauncher.cmds(tmpDir + "\\\\" + runnerScriptName, "\\"" + matlabCommand + "\\"")
                    .stdout(listener);

(2) Output of java.io.tmpdir in Windows OS.  accodring to the following web "java.io.tmpdir Inconsitency": 
  https://rationalpi.wordpress.com/2007/01/26/javaiotmpdir-inconsitency/

**Comment by wyoshio** [comment]
In addition, I modified my first comment, because markdown treated and changed 'backslash' as special character. I didn't realize it.

**Comment by nbhoski** [comment]
ok looking into it.

**Comment by abhargav-mw** [comment]
Hi Yoshio,

The log that you shared suggests it's a warning and not an error. Also, the warning seems to be for the file mentioned in the next line,
"C:\ProgramData\MATLAB\SupportPackages\R2020a\... ...\registry "

This seems to be coming from matlab -batch execution. Can you check if the aforementioned file exists?

To counter check, given you are executing runMatlabTests, can you enable all the configure options under 'Generate Test Artifacts' and then post build, check the 'Workspace' for the Project to see if all artifacts are generated. That should confirm plugin worked correctly.

**Comment by wyoshio** [comment]
Thank you. As you say, the warning comes from other add-on installation in my PC, and doesn't related to this plugin.
Actual problem seems my repository setting in the jenkins project and it has no unit test cases.
