### ISSUE TITLE
startup.m file not executing when starting Matlab job

### ISSUE THREAD

**Issue by geerligs** [mathworks/jenkins-matlab-plugin#117]
When the job workspace contains a startup.m file, this is not executed by default. In the previous version of the Jenkins plugin Matlab was started in the job workspace and  when a startup.m was present this was executed.
With the current jenkins plugin Matlab will not start in the job workspace and will perform a change directory in the (generated) command file. So any startup.m file in the job workspaced is not executed auutomatically.

Right now as a workaround I am using the command sequence "startup;sl_refresh_customizations;". 

I was wondering why this behaviour was changed, and whether breaking the startup-file was considered?

regards, Han Geerligs

**Comment by nbhoski** [comment]
Thanks  for bringing this up @geerligs looking into this

**Comment by geerligs** [comment]
As an addition, the issue is only true for the step runMatlabCommand, not for the step runMatlabTests

**Comment by acampbel** [comment]
Thanks for reporting! This is not intended and we will get a patch release out soon. You should be able to leverage/reply on startup.m.

This wasn't due to official pipelines support, but rather a more robust, shell independent way to execute matlab commands. But this startup use case was missed.

**Comment by nbhoski** [comment]
@geerligs  fix for this issue is released in version 2.1.1 and is available on Jenkins marketplace now.

**Comment by geerligs** [comment]
Hi Nikhil,
Thanks for mentioning. I have tested it and startup.m is now run when starting.
Han
Get Outlook for Android
Van: Nikhil Bhoski <notifications@github.com>
Verstuurd: woensdag 22 juli 2020 18:09
Aan: mathworks/jenkins-matlab-plugin
Cc: Han Geerligs; Mention
Onderwerp: Re: [mathworks/jenkins-matlab-plugin] startup.m file not executing when starting Matlab job (#117)






Closed #117.
