### ISSUE TITLE
Configuration of artifacts generation is not permanently saved in Run MATLAB Tests mode

### ISSUE THREAD

**Issue by pablorcum** [mathworks/jenkins-matlab-plugin#118]
I noticed that after upgrading the MATLAB plugin for Jenkins to version 2.1.0, the checkbox for generation of the TAP report in the Run MATLAB Tests does not get saved in my job configuration. It gets unchecked automatically after running the job.

**Comment by SangaviJayagopi** [comment]
@pablorcum 

Sorry, I am not able to reproduce the issue. Did you mean, after you run the job, going back to the Configure page, TAP check box got unchecked? 

Could you give the complete reproduction steps for the issue and details on environment you are running in?
