### ISSUE TITLE
Test artifact checkbox does not retain values after plugin update

### ISSUE THREAD

**Issue by nbhoski** [mathworks/jenkins-matlab-plugin#132]
for run MatlabTests builder step the test artifact values does not retain the previous selection after the plugin is updated it to ewer version.

**Comment by acampbel** [comment]
yikes. this is a bad bug given there is data loss. we should prioritize this fix.

**Comment by SangaviJayagopi** [comment]
Closing the after verification [branch hot_fixes_issue_132](https://github.com/mathworks/jenkins-matlab-plugin/pull/136)
