### ISSUE TITLE
Increase verbosity level by default with Run MATLAB Tests mode

### ISSUE THREAD

**Issue by pablorcum** [mathworks/jenkins-matlab-plugin#145]
When using the Run MATLAB Tests mode the text output in the console is in my opinion too poor. For example, it does not provide any information about the current status or execution of different test cases. You only know which test folder is being executed, that means that for test suites with many different test cases, the console may not display new information for a long time.

The matlab.unittest.TestRunner.withTextOutput allows setting different levels for LoggingLevel and OutputDetail. I found out that OutputDetail = 3 provides a good trade-off between console text length and useful information. Please consider increasing the output detail so that the console display info about running and done of single test cases.

**Comment by nbhoski** [comment]
Thanks @pablorcum . We will definitely consider this in future releases. Also, we are working on making such options configurable through UI or providing appropriate step parameters.

**Comment by ranford** [comment]
Hello @pablorcum,

The output detail has been at level 3 in recent releases. Can you confirm that this is resolved?

Thanks,
Andy

**Comment by acampbel** [comment]
Hi @pablorcum,

This should be using verbosity 3 in recent releases of the plugin. Can you confirm this is that case so we don't miss anything?

Thanks,
Andy
