### ISSUE TITLE
runMatlabTests.m script from older builds exists in workspace after the plugin upgrade

### ISSUE THREAD

**Issue by SangaviJayagopi** [mathworks/jenkins-matlab-plugin#151]
After updating the plugin with genscript changes, when running build on older project, the runMatlabtests.m is present.

**Comment by nbhoski** [comment]
We dont delete this file generated from older builds. however new build will not generate it in the workspace.

**Comment by SangaviJayagopi** [comment]
In the pipeline projects, newer builds have the script 'runMatlabTests.m' from the older ones.  Closing this, assuming this is expected.
