### ISSUE TITLE
Text Input for artifacts such as: matlabTestArtifact's/taptestresults.tap causes build failure

### ISSUE THREAD

**Issue by SangaviJayagopi** [mathworks/jenkins-matlab-plugin#152]
Console log at the end of the build:

Started by user Sangavi Jayagopi
Running as SYSTEM
Building on master in workspace /Users/sjayagop/.jenkins/workspace/test_genscript
[test_genscript] $ /var/folders/bc/l10_249126g1thr9hhsv2wj4000fnq/T/f1193c2c-d422-4f89-94ee-850f2b0133d6/run_matlab_command.sh "addpath('/var/folders/bc/l10_249126g1thr9hhsv2wj4000fnq/T/f1193c2c-d422-4f89-94ee-850f2b0133d6'); test_runner_f1193c2c_d422_4f89_94ee_850f2b0133d6"
{Error: File:
/private/var/folders/bc/l10_249126g1thr9hhsv2wj4000fnq/T/f1193c2c-d422-4f89-94ee-850f2b0133d6/test_runner_f1193c2c_d422_4f89_94ee_850f2b0133d6.m
Line: 1 Column: 326
Invalid expression. Check for missing multiplication operator, missing or
unbalanced delimiters, or other syntax error. To construct matrices, use
brackets instead of parentheses.
} 
Build step 'Run MATLAB Tests' changed build result to FAILURE
Finished: FAILURE

**Comment by nbhoski** [comment]
I guess @abhargav-mw  has already fixed it in recent PR. we could bring that fix on QE branch .

**Comment by abhargav-mw** [comment]
The issue seems to be with freestyle projects and Scriptgen as well. I have fixed the plugin to handle apostrophes and scriptgen as well. Scriptgen will take a while to be published.

**Comment by SangaviJayagopi** [comment]
Verified in 2.1.4 Qualification
