### ISSUE TITLE
For version R2017a , R2017b build fails with error using eval

### ISSUE THREAD

**Issue by SangaviJayagopi** [mathworks/jenkins-matlab-plugin#154]
Build log:

Started by user Sangavi Jayagopi
Running as SYSTEM
Building on master in workspace /Users/sjayagop/.jenkins/workspace/test_genscript
using credential 5f59e6e8-8b32-4c30-8461-bd17c2ac4fac
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/mathworks/ci-test-repo # timeout=10
Fetching upstream changes from https://github.com/mathworks/ci-test-repo
 > git --version # timeout=10
using GIT_ASKPASS to set credentials 
 > git fetch --tags --force --progress -- https://github.com/mathworks/ci-test-repo +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision 453bc666d454c957d0fa2aa8880245c0a4b96582 (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 453bc666d454c957d0fa2aa8880245c0a4b96582 # timeout=10
Commit message: "Update startup.m"
 > git rev-list --no-walk 0704b14d1a27198cf2b027b85a1ef480d4589953 # timeout=10
[test_genscript] $ /var/folders/bc/l10_249126g1thr9hhsv2wj4000fnq/T/0a2785ff-9a9d-42e8-b4ee-0bbd8aa0fc0a/run_matlab_command.sh "addpath('/var/folders/bc/l10_249126g1thr9hhsv2wj4000fnq/T/0a2785ff-9a9d-42e8-b4ee-0bbd8aa0fc0a'); test_runner_0a2785ff_9a9d_42e8_b4ee_0bbd8aa0fc0a"

                            < M A T L A B (R) >
                  Copyright 1984-2017 The MathWorks, Inc.
                   R2017a (9.2.0.556344) 64-bit (maci64)
                               March 27, 2017

This is the .matlabrc
************STARTUP FILE**************
/Users/sjayagop/.jenkins/workspace/test_genscript/startup.m
Error using eval
Undefined function 'addpath' for input arguments of type 'char'.
Build step 'Run MATLAB Tests' changed build result to FAILURE
Finished: FAILURE

**Comment by nbhoski** [comment]
Is this running on windows ? or on remote ? i am not sure it says `Building on master in workspace /Users/sjayagop/.jenkins/workspace/test_genscript` but then your Temp folder structure looks non windowee `/var/folders/bc/l10_249126g1thr9hhsv2wj4000fnq/T/`

**Comment by abhargav-mw** [comment]
The issues seems to be stemming from the fact that matlabrc shouldn't be overridden. It seems overriding that file messes with MATLAB initialization. I'd suggest you remove matalbrc from your repo.
