### ISSUE TITLE
Error using matlab.unittest.internal.folderResolver 

### ISSUE THREAD

**Issue by SangaviJayagopi** [mathworks/jenkins-matlab-plugin#167]
Reproduction steps:

1. Create a fork from https://github.com/mathworks/ci-test-repo
     Note in the pipeline script: **testResultsTAP: 'new-results/results.tap'**
2. Create a new pipeline project configuration in Jenkins by pointing to this Github repo
3. Build the project, the project is built successfully
4. Change the pipeline script to have: **testResultsTAP: **'new-result*$^s/results.tap'****
5. Build the project, the project is built successfully
6. Change the pipeline to the original:  **testResultsTAP: 'new-results/results.tap'**
7. Build the project again, you will see the error 

Error in matlab.unittest.TestSuite.fromFolder (line 545)
            fullFolderPath = folderResolver(folder);

Error in
matlab.unittest.TestSuite>@(fld)TestSuite.fromFolder(fld,selector,'IncludingSubfolders',includeSubfolders)
(line 599)
            subSuites = arrayfun(@(fld) TestSuite.fromFolder(fld,
            selector,'IncludingSubfolders',includeSubfolders), ...

Error in matlab.unittest.TestSuite.fromFolder (line 599)
            subSuites = arrayfun(@(fld) TestSuite.fromFolder(fld,
            selector,'IncludingSubfolders',includeSubfolders), ...

Error in
matlab.unittest.TestSuite>@(fld)TestSuite.fromFolder(fld,selector,'IncludingSubfolders',includeSubfolders)
(line 599)
            subSuites = arrayfun(@(fld) TestSuite.fromFolder(fld,
            selector,'IncludingSubfolders',includeSubfolders), ...

Error in matlab.unittest.TestSuite.fromFolder (line 599)
            subSuites = arrayfun(@(fld) TestSuite.fromFolder(fld,
            selector,'IncludingSubfolders',includeSubfolders), ...

Error in testsuite>createSuite (line 221)
    suite = TestSuite.fromFolder(folder, selector, 'IncludingSubfolders',
    includeSubfolders);

**Comment by mcafaro** [comment]
Can you please post the content of the generated script?

**Comment by SangaviJayagopi** [comment]
Sure. Here goes:

Running MATLAB script with content:
import matlab.unittest.TestRunner;
import matlab.unittest.Verbosity;
import matlab.unittest.plugins.CodeCoveragePlugin;
import matlab.unittest.plugins.TAPPlugin;
import matlab.unittest.plugins.ToFile;
import matlab.unittest.plugins.XMLPlugin;
import matlab.unittest.plugins.codecoverage.CoberturaFormat;
import sltest.plugins.ModelCoveragePlugin;
import sltest.plugins.TestManagerResultsPlugin;

addpath(genpath('/Users/sjayagop/Desktop/src'));
addpath(genpath('/Users/sjayagop/Desktop/test'));

suite = testsuite(pwd, 'IncludeSubfolders', true);

[~,~] = mkdir('new-coverage');
[~,~] = mkdir('new-results');

if exist(fullfile(pwd, 'new-results/results.tap'), 'file') == 2
    delete('new-results/results.tap');
end

runner = TestRunner.withTextOutput('OutputDetail', Verbosity.Detailed);
runner.addPlugin(TAPPlugin.producingVersion13(ToFile('new-results/results.tap')));
runner.addPlugin(XMLPlugin.producingJUnitFormat('new-results/results.xml'));
runner.addPlugin(TestManagerResultsPlugin('ExportToFile', 'new-results/results.mldatx'));
runner.addPlugin(CodeCoveragePlugin.forFolder({'/Users/sjayagop/Desktop/src', '/Users/sjayagop/Desktop/test'}, 'IncludingSubfolders', true, 'Producing', CoberturaFormat('new-coverage/coverage.xml')));
runner.addPlugin(ModelCoveragePlugin('Producing', CoberturaFormat('new-coverage/coverage.xml')));

results = runner.run(suite);

nfailed = nnz([results.Failed]);
assert(nfailed == 0, [num2str(nfailed) ' test(s) failed.']);

**Comment by mcafaro** [comment]
This appears to be an issue with `testsuite` and not the Jenkins plugin or scriptgen in particular.

```
>> mkdir("new-result'*$^s/new-result'*$^s'")
>> testsuite(pwd,"IncludeSubfolders",true)
Error using matlab.unittest.internal.folderResolver (line 14)
Folder "/Users/mcafaro/Documents/MATLAB/New Folder (4)/new-result'*$^s/new-result'*$^s" cannot be found.

Error in matlab.unittest.TestSuite.fromFolder (line 545)
            fullFolderPath = folderResolver(folder);

Error in matlab.unittest.TestSuite>@(fld)TestSuite.fromFolder(fld,selector,'ExternalParameters',externalParameters,'IncludingSubfolders',true) (line 566)
                subSuites = arrayfun(@(fld) TestSuite.fromFolder(fld, selector, ...

Error in matlab.unittest.TestSuite.fromFolder (line 566)
                subSuites = arrayfun(@(fld) TestSuite.fromFolder(fld, selector, ...

Error in matlab.unittest.TestSuite>@(fld)TestSuite.fromFolder(fld,selector,'ExternalParameters',externalParameters,'IncludingSubfolders',true) (line 566)
                subSuites = arrayfun(@(fld) TestSuite.fromFolder(fld, selector, ...

Error in matlab.unittest.TestSuite.fromFolder (line 566)
                subSuites = arrayfun(@(fld) TestSuite.fromFolder(fld, selector, ...

Error in testsuite>createSuite (line 223)
    suite = TestSuite.fromFolder(folder, selector, 'IncludingSubfolders', includeSubfolders);

Error in testsuite (line 130)
    suites{k} = createSuite(testAsChar, selector, ...
```

Please file with the unit test frameworks team.
