### ISSUE TITLE
Error while using Tool configuration on Node(Restricting the build on the configured node only)

### ISSUE THREAD

**Issue by Vahila** [mathworks/jenkins-matlab-plugin#180]
I have R2020a MATLAB installed and configured globally as 'ML_2020a' on both Master and Node(Linux).

In Free Style project, I have restricted the agent using 'Restrict where this project can be run' from General settings to the Node (Linux machine). I have tried the following two scenarios for specifying MATLAB:

- In 'Use MATLAB Version', 'ML_2020a' is selected. The build is failing with below error:

Building remotely on Linux (linuxVM) in workspace /var/jenkins/workspace/free-ci-test
FATAL: Unable to launch MATLAB 'ML_2020a' on the node 'Linux'. Verify global tool configuration for the specified node.
com.mathworks.ci.MatlabNotFoundError: Unable to launch MATLAB 'ML_2020a' on the node 'Linux'. Verify global tool configuration for the specified node.

Expectation:
As the Tool config 'ML_2020a' is present in both Master and Node, the build should be able to pick MATLAB from Node.

- If in 'Use MATLAB Version', 'Custom' is selected and same path as specified in Node's 'ML_2020a' Global Tool Config, the build is successful.

**Comment by nbhoski** [comment]
@Vahila can you also try it by setting master executor to 0 threads and without restricting the job run on specific node. see if Jenkins automatically load balances it with existing MATLAB .

**Comment by Vahila** [comment]
> @Vahila can you also try it by setting master executor to 0 threads and without restricting the job run on specific node. see if Jenkins automatically load balances it with existing MATLAB .

The error is still occurring when the executors in master are set to 0 and with no restriction.

**Comment by Vahila** [comment]
The error was occurring because of the configuration issues on Node. The build is successful after changing the configurations.
