### ISSUE TITLE
Update the document and Wiki with Simulink 

### ISSUE THREAD

**Issue by nbhoski** [mathworks/jenkins-matlab-plugin#21]
Update the required document and or Wiki or both to make this plugin searchable with keyword Simulink.

**Comment by nbhoski** [comment]
Updated Wiki with Simulink word to make it discover able through google search.
@mw-hrastega you could review https://wiki.jenkins.io/display/JENKINS/MATLAB+Plugin as well and suggest me if any changes required.

**Comment by mw-hrastega** [comment]
Hi Nikhil,

I am attaching my suggested edits.

Thanks,
Houman

[MATLAB Plugin - Jenkins - Jenkins Wiki_HR.pdf](https://github.com/mathworks/jenkins-matlab-plugin/files/3162569/MATLAB.Plugin.-.Jenkins.-.Jenkins.Wiki_HR.pdf)

**Comment by nbhoski** [comment]
Thanks Houman ,
May i request you to approve of the pull request, if you dont see any major flag in the files that we changed. Which is independent of Wiki page. it would help me merge these changes and work towards the next release.

**Comment by nbhoski** [comment]
Closing the Issue as Documet and Ined.jelly is updated accordingly and released in the version 1.0.1 version
