### ISSUE TITLE
missing console output for old matlab releases

### ISSUE THREAD

**Issue by geerligs** [mathworks/jenkins-matlab-plugin#210]
Hello,

when using an old Matlab release (R2012a and older) I noticed that the console output is not available.
I remember that this might be solved by running <matlabroot>/bin/win32/matlab.exe instead of <matlabroot>/bin/matlab.exe.

Can you comment on this?

kind regards, Han

**Comment by nbhoski** [comment]
Hi @geerligs thanks for this issue, However based on wider customer feedback and most commonly supported features for CI in MATLAB we reached to careful  business decision of supporting the plugin officially from R2013b onwards. Prior versions to it currently is out of scope for Jenkins plugin support. for all prior versions you may have to either use shell/batch script to run MATLAB task   as described in this blog https://blogs.mathworks.com/developer/2015/01/20/the-other-kind-of-continuous-integration/ by @acampbel

**Comment by geerligs** [comment]
Hi Nikhil,

thanks for your reply. Your suggestion on using a shell script is actually feasible, however you need to add some error catching.

--Han

**Comment by nbhoski** [comment]
Yes, you are right probably for that you can look at https://github.com/mathworks/jenkins-matlab-plugin/blob/71d98da5332cdbd1920d41b3a522f793a4ab76a9/src/main/java/com/mathworks/ci/MatlabBuilder.java#L592 which may give you some hint on how we handled try catch in CLI mode

**Comment by geerligs** [comment]
Nikhil, thanks for the hint!

--Han
