### ISSUE TITLE
Allow MATLAB to run with other critical startup options 

### ISSUE THREAD

**Issue by nbhoski** [mathworks/jenkins-matlab-plugin#216]
With  reference to Braess Hennings Mails which is quoted below. It seems we shall allow user to use some of the essential MATLAB startup options in this case its was `-c` to provide `.lic` file explicitly. 

" Dear Sir or Madam
 
we are currently encountering issues with our license management. In order to avoid these issues your collegues from MathWorks tech-support suggested that I call matlab with a specific license file
 
"C:\Program Files\MATLAB\R2022a\bin\matlab.exe" -c "C:\Program FIles\MATLAB\R2022a\licenses\network.lic"
 
instead of just calling
 
matlab
 
On the command line this is very simple. But normally I use the Jenkins server and I use the build-step “add matlab command”. What do you suggest, what is the best way to proceed with calling a specific license file on a Jenkins.
 
Of course I could use the Windows command shell on Jenkins and call matlab with the -batch option. Is this completely equivalent to the “add matlab command” build step in Jenkins? I usually define the parameters parameter1 and parameter2 on Jenkins and I hand them over to my matlab function  via:
 
runMyScript(${parameter1}, ${parameter2})
 
Yours Henning Braess "

**Comment by sameagen-MW** [comment]
I think this has been completed with the switch to using RMC and supporting start up options. Feel free to reopen if not.
