### ISSUE TITLE
Tests are defaulted to run in serial when PDF artifact is generated with new GenScript changes

### ISSUE THREAD

**Issue by Vahila** [mathworks/jenkins-matlab-plugin#225]
When the tests are opted to be run in parallel and PDF artifact generation is selected a warning is thrown as below and tests are run in serial. Is this the expected behavior?

> [sampleRepo_Free_Artifacts] $ cmd.exe /C .matlab\eVVe438q\run_matlab_command.bat '"addpath('C:\Users\vkayithi\AppData\Local\Jenkins\.jenkins\workspace\sampleRepo_Free_Artifacts/.matlab/eVVe438q'); runner_eVVe438q,delete('.matlab/eVVe438q/runner_eVVe438q.m'),runnerScript,rmdir(tmpDir,'s')"'
Starting parallel pool (parpool) using the 'local' profile ...
Connected to the parallel pool (number of workers: 6).
[Warning: Unable to generate all artifacts while running tests in parallel. Running tests in serial instead.] 
[> In scriptgen.internal.scripts/TestScriptBuilder/build (line 46)
In scriptgen/CodeProvider/createCode (line 104)
In scriptgen/CodeProvider/createScript (line 72)
In genscript (line 24)
In runner_eVVe438q (line 6)] 
Running MATLAB script with content:
import matlab.unittest.TestRunner;
import matlab.unittest.plugins.FailOnWarningsPlugin;
import matlab.unittest.plugins.TestReportPlugin;
import sltest.plugins.TestManagerResultsPlugin;

addpath(genpath('src'));

suite = testsuite(pwd, 'IncludeSubfolders', true);

[~,~] = mkdir('matlabTestArtifacts');

% Unable to generate all artifacts while running tests in parallel. Running tests in serial instead.

runner = TestRunner.withTextOutput();
runner.addPlugin(FailOnWarningsPlugin());
runner.addPlugin(TestReportPlugin.producingPDF('matlabTestArtifacts/testreport.pdf'));
runner.addPlugin(TestManagerResultsPlugin());

results = runner.run(suite);
display(results);

assertSuccess(results);

**Comment by mcafaro** [comment]
Depends on the release you're running under. PDF and HTML test reports cannot be produced in parallel until 22b because of the inclusion of TestManagerResultsPlugin.

**Comment by Vahila** [comment]
Okay. thank you Mark for the inputs. Closing the issue.
