### ISSUE TITLE
Help text missing for Startup options

### ISSUE THREAD

**Issue by Vahila** [mathworks/jenkins-matlab-plugin#254]
There is no help text provided for the Startup options

**Comment by sameagen-MW** [comment]
Hey Vahila, could you provide reproduction instructions so I can figure out exactly where it's missing? There's a couple of different places that the startup options text shows up

**Comment by Vahila** [comment]
> Hey Vahila, could you provide reproduction steps so I can figure out exactly where it's missing? There's a couple of different places that the startup options text shows up

The '?' help symbol in the build step beside the Startup Options text is missing.

**Comment by sameagen-MW** [comment]
Note for myself before I forget:
* Specifically missing in Freestyle UI. Double check StartupOptions.jelly
* Appears that the StartupOptions folder is missing in this fork.

**Comment by sameagen-MW** [comment]
Hey Vahila,

I'm having trouble reproducing this issue. Could you provide your platform info + precise steps of how you built and deployed the plugin?

Thanks!

**Comment by sameagen-MW** [comment]
If you built and HPI file as part of that process, could you also send that to me over Teams or email?

**Comment by Vahila** [comment]
> Hey Vahila,
> 
> I'm having trouble reproducing this issue. Could you provide your platform info + precise steps of how you built and deployed the plugin?
> 
> Thanks!

Hi Sam,

I generated the hpi file by running mvn install and uploaded the hpi file in Jenkins server running on Windows machine. I will email the hpi file.

Thanks,
Vahila.

**Comment by Vahila** [comment]
Hey Sam,

With the new changes I can see the help section beside the text box. But can we have it beside the 'Startup options' text to be consistent?
![image](https://github.com/mathworks/jenkins-matlab-plugin/assets/70003902/fdbe6a12-e7e0-4a88-b320-032fb63759fa)

Thanks,
Vahila.

**Comment by sameagen-MW** [comment]
Completed!
