### ISSUE TITLE
'-logfile output.log -nosplash' startup option does not generate the log file 

### ISSUE THREAD

**Issue by Vahila** [mathworks/jenkins-matlab-plugin#255]
I tried giving the startup options as '-logfile output.log -nosplash' through MATLAB Jenkins plugin but I do not see the log file generated. When I try the same options through CMD using 'matlab -batch version -logfile output.log -nosplash' I can see the log file generated in the directory.

**Comment by Vahila** [comment]
In Jenkins logs, I get the warning as below:

#################### Starting command output ####################
[free] $ C:\ProgramData\Jenkins\.jenkins\workspace\free\.matlab\ZoYv1o41\run-matlab-command.exe "cd('C:\ProgramData\Jenkins\.jenkins\workspace\free/.matlab/ZoYv1o41');command_P444KkwT" "-logfile output.log -nosplash"
**[Warning: Unrecognized command line option: logfile output.log -nosplash.]** 

I get the same warning from CMD MATLAB with -batch when passing the startup options as `matlab -batch version "-logfile output.log -nosplash"` instead of `matlab -batch version -logfile output.log -nosplash`

**Comment by sameagen-MW** [comment]
I think that this is likely due to a difference in how Linux and Windows shells handle strings. I'll look into it but could you give some more information, specifically:

1. What entry field are you using to specify startup options?
2. What version of MATLAB are you using?
3. What version of Windows are you using?

**Comment by sameagen-MW** [comment]
The fix should be merged, I'll wait for your confirmation that the issue has been resolved before closing this.

**Comment by Vahila** [comment]
The fixes have resolved the issue. Closing this issue.
