### ISSUE TITLE
MATLAB Build Results doesn't show tasks even though tasks are run in an existing project

### ISSUE THREAD

**Issue by Vahila** [mathworks/jenkins-matlab-plugin#280]
I have an existing project which has buildfile in the workspace. The MATLAB Build Tasks shows 0 tasks are run even when 3 tasks are run.
![image](https://github.com/mathworks/jenkins-matlab-plugin/assets/70003902/15d8d15b-7d32-46e5-b130-5bd4a9e3b4f0)

![image](https://github.com/mathworks/jenkins-matlab-plugin/assets/70003902/92ce3188-7707-444b-8db8-a41ce6f355d8)

 When used the same buildfile in new project, the summary and table show expected metrics

**Comment by nbhoski** [comment]
Looks like you may be running on older MATLAB which does not support invoking the plugin explicitly

**Comment by Vahila** [comment]
In 2024a, this works as expected.
