### ISSUE TITLE
MATLAB Build results are not populated when buildfile is present in a different folder 

### ISSUE THREAD

**Issue by Vahila** [mathworks/jenkins-matlab-plugin#281]
The buildfile was present in folder1. So, I specified the working folder for the project as folder1. When the build is finished, the MATLAB Build Results are not populated correctly. Since 3 tasks were run as part of the project build, I was expecting the correct metrics to be shown.

**Comment by Vahila** [comment]
Build step with -sd option generates an error.
![image](https://github.com/mathworks/jenkins-matlab-plugin/assets/70003902/eab93290-0574-475d-9c16-bdd885b27691)
![image](https://github.com/mathworks/jenkins-matlab-plugin/assets/70003902/66ce51b3-f25b-4741-a548-ca177dbcd333)

**Comment by nbhoski** [comment]
@Vahila this still persists ?

**Comment by Vahila** [comment]
This works as expected with new changes.
