### ISSUE TITLE
Confusing Build results when using previous versions(23b) of MATLAB

### ISSUE THREAD

**Issue by Vahila** [mathworks/jenkins-matlab-plugin#283]
When Jenkins job is run in 23b or prior, the MATLAB Build Results shows that 0 tasks are run(even though build tasks are run) which is a bit misleading. The user needs to know that the results are populated correctly with 24a

**Comment by nbhoski** [comment]
@davidbuzinski  do we have any plans pathich previous MATLAB releases for supporting explicit plugin injection ?

**Comment by davidbuzinski** [comment]
> @davidbuzinski do we have any plans pathich previous MATLAB releases for supporting explicit plugin injection ?

The patches have been submitted for all previous releases including buildtool. I think there should be an update that includes the changes for most releases now. Make sure to update to the latest update release to see the changes

**Comment by mw-hrastega** [comment]
> May be this could be documented at some place. The design in itself runs the build visulization irrespective of MATLAB version. Also we need to know what are the plans for backporting Davids changes to MATLAB versions that support buildtool.

Hi, @nbhoski. Can you first try @davidbuzinski's answer? If the issue doesn't get resolved, then we can find a way to point to this bug/limitation in the doc.

**Comment by nbhoski** [comment]
> > @davidbuzinski do we have any plans pathich previous MATLAB releases for supporting explicit plugin injection ?
> 
> The patches have been submitted for all previous releases including buildtool. I think there should be an update that includes the changes for most releases now. Make sure to update to the latest update release to see the changes

@Vahila  could you try this and let me know if this issue persists

**Comment by Vahila** [comment]
@davidbuzinski @nbhoski  MATLAB Build Results are populated correctly for 23b U6.

For 23a U6, there is an error as below:
![image](https://github.com/mathworks/jenkins-matlab-plugin/assets/70003902/9e463eab-2069-4e98-b847-a93c7ba6e344)
I see similar error in 23a GR as well
![image](https://github.com/mathworks/jenkins-matlab-plugin/assets/70003902/c8bc9536-af5c-4301-8aaa-8ddc067aa33a)


For22b U7, the error is as below:
![image](https://github.com/mathworks/jenkins-matlab-plugin/assets/70003902/dface0b1-577d-4c7e-9246-ac396b493b82)

I have checked till 22b as buildtool is supported from 22b.

**Comment by davidbuzinski** [comment]
> @davidbuzinski @nbhoski MATLAB Build Results are populated correctly for 23b U6.
> 
> For 23a U6, there is an error as below: ![image](https://private-user-images.githubusercontent.com/70003902/301755388-9e463eab-2069-4e98-b847-a93c7ba6e344.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4ODQ3NDcsIm5iZiI6MTcwNjg4NDQ0NywicGF0aCI6Ii83MDAwMzkwMi8zMDE3NTUzODgtOWU0NjNlYWItMjA2OS00ZTk4LWI4NDctYTkzYzdiYTZlMzQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDE0MzQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyMzI4NjBmOTE3MDdmMjU4NjI4ODA0Zjk1MGFjNzVhYTc2NGUzNWVhMDI4YTU2Y2I4ZjkyYjAzMDg0MzhkNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c89JHMXF4QXv7InNKx7FH2mC3yTqD7_gBKOpqANIgXI) I see similar error in 23a GR as well ![image](https://private-user-images.githubusercontent.com/70003902/301757923-c8bc9536-af5c-4301-8aaa-8ddc067aa33a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4ODQ3NDcsIm5iZiI6MTcwNjg4NDQ0NywicGF0aCI6Ii83MDAwMzkwMi8zMDE3NTc5MjMtYzhiYzk1MzYtYWY1Yy00MzAxLThhYWEtOGRkYzA2N2FhMzNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDE0MzQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwZDc1NzYxOTE4Y2RkNjBkZWNkNzQxYWU2MDYyOTg1NGNmNzkyYzNjOTgwMmUzYjA3ODBmMWEwYjkwZDM2ZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NETIsO60O9EOKnVR_LeXS-rtUJnpAvNurqSNXx5Mbx0)
> 
> For22b U7, the error is as below: ![image](https://private-user-images.githubusercontent.com/70003902/301758324-49736504-77c8-43e9-9068-f2ef35c05ee2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4ODQ3NDcsIm5iZiI6MTcwNjg4NDQ0NywicGF0aCI6Ii83MDAwMzkwMi8zMDE3NTgzMjQtNDk3MzY1MDQtNzdjOC00M2U5LTkwNjgtZjJlZjM1YzA1ZWUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDE0MzQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwNTM0NDc0N2JmODNiZjNlNzZiNzY1NWIxOTM1ZTZmMDkxYjU4NDQyODQ2NTBjODY1NzgyYjAzOGQyMjRiZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SbYcqgqpazjAoWnvL3g_GNa2G344Et8y8Y-kbyk6ch0)
> 
> I have checked till 22b as buildtool is supported from 22b.

It looks like the buildfile.m that is being tested is using features from buildtool that weren't released yet at the time of several of the releases being tested

**Comment by Vahila** [comment]
I can see the Build Results getting populated correctly for 22bU8, 23aU6, 23bU6.

**Comment by nbhoski** [comment]
@Vahila can we close this in that case

**Comment by Vahila** [comment]
Can we also discuss this in the team meeting? Based on that we can take an action.

**Comment by Vahila** [comment]
Closing this issue as we have another issue to discuss about the warning message: https://github.com/mathworks/jenkins-matlab-plugin/issues/288
