### ISSUE TITLE
Artifacts from Run MATLAB Tests are not generated in workspace when using -sd option

### ISSUE THREAD

**Issue by Vahila** [mathworks/jenkins-matlab-plugin#287]
When -sd option is used with Run MATLAB Tests, the artifacts are are generated  in the specified initial folder and not in the workspace. Is this expected?

**Comment by nbhoski** [comment]
@Vahila is it verified

**Comment by Vahila** [comment]
> @Vahila is it verified

Yes, attaching screenshots for reference:

![image](https://github.com/mathworks/jenkins-matlab-plugin/assets/70003902/d534c645-3ea0-4962-b712-590701e81e6c)
![image](https://github.com/mathworks/jenkins-matlab-plugin/assets/70003902/7c0943af-0ad1-47bf-88f1-5812d1508b23)

Console output:
![image](https://github.com/mathworks/jenkins-matlab-plugin/assets/70003902/89f77af7-2dea-4f25-b578-c7a2fe39dc65)

I also see a warning:
![image](https://github.com/mathworks/jenkins-matlab-plugin/assets/70003902/51e94d41-cc7d-4245-b2bf-293de5faf58c)

Artifacts are not generated in workspace:
![image](https://github.com/mathworks/jenkins-matlab-plugin/assets/70003902/f1fc43e8-0384-4025-990c-40995fa66538)

**Comment by sameagen-MW** [comment]
@nbhoski are you looking into this or should I check it out? My first thought without looking into it too much is  that we might need to adjust the genscript to use the workspace dir.

**Comment by nbhoski** [comment]
> I think I lean more towards generating the artifacts relative to the Jenkins workspace. I think it's probably more standard for Jenkins users to expect relative paths to resolve relative to the workspace rather than the MATLAB startup directory. If we did decide to keep the behavior like it is right now, I think we'd probably have to clarify somewhere in the documentation.

Yes thats what the dilema is. Prolly we could discuss this in our team meeting for some more feedback

**Comment by nbhoski** [comment]
After discussion to support substitution ${WORKSPACE} we are keeping the behaviour as is. Closing the issue
