### ISSUE TITLE
The build summary should not include an ordered list (1., 2.)

### ISSUE THREAD

**Issue by mw-hrastega** [mathworks/jenkins-matlab-plugin#289]
Please replace the ordered list in the build summary (1. and 2. ) with an unordered list (bullet points). We should use an ordered list only if the order matters.

**Comment by nbhoski** [comment]
Fixed

**Comment by Vahila** [comment]
The bullet points are changed as shown below:
![image](https://github.com/mathworks/jenkins-matlab-plugin/assets/70003902/b21c7fe7-8fc6-418c-9d32-079ab5d4e539)

**Comment by mw-hrastega** [comment]
Hi, @nbhoski and @Vahila. After brainstorming with @sameagen-MW, I feel that we can improve the summary and be more consistent with other sections by streamlining the text and removing some of the whitespace. Can you please update the text and line spacing as follows? Thanks.


### MATLAB Build Result
**Tasks Run:** 3
**Failed:** 0
**Skipped:** 0

**Comment by nbhoski** [comment]
Fixed

**Comment by mw-hrastega** [comment]
> Fixed

Thanks, @nbhoski . @Vahila, could you please verify the change and then attach a screenshot?

**Comment by nbhoski** [comment]
<img width="374" alt="image" src="https://github.com/mathworks/jenkins-matlab-plugin/assets/47204011/7ee071ee-8449-4470-b358-96a155156d12">

**Comment by Vahila** [comment]
The summary is updated as below
![image](https://github.com/mathworks/jenkins-matlab-plugin/assets/70003902/b8bc7ecc-87ea-46a2-95fc-fae4fa4ad4ed)

**Comment by mw-hrastega** [comment]
Thanks, @nbhoski. A few things to consider:

- "Task run" should be "Tasks run" (missing s).
- "Tasks run:", "Failed:", and "Skipped:" should be bolded.
- The line spacing is quite large and makes the list elements disconnected.

**Comment by nbhoski** [comment]
fixed
<img width="253" alt="image" src="https://github.com/mathworks/jenkins-matlab-plugin/assets/47204011/7f808d8b-b4d8-4ce9-aec9-9a8641663bb8">

**Comment by nbhoski** [comment]
Fixed 
<img width="269" alt="image" src="https://github.com/mathworks/jenkins-matlab-plugin/assets/47204011/1f02409c-1425-4e4a-ba5b-f67e8c482111">

**Comment by mw-hrastega** [comment]
> Fixed <img alt="image" width="269" src="https://private-user-images.githubusercontent.com/47204011/306503485-1f02409c-1425-4e4a-ba5b-f67e8c482111.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MjQxMDIsIm5iZiI6MTcwODUyMzgwMiwicGF0aCI6Ii80NzIwNDAxMS8zMDY1MDM0ODUtMWYwMjQwOWMtMTQyNS00ZTRhLWJhNWItZjY3ZThjNDgyMTExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDEzNTY0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzY2NmNGMwOGE2ZWNmNGY5Y2M4OWY5YWM4M2Q0YTBlMWMyNzUzYjNhNzlhMDM5Y2U3YTc4YjYyNGVhNTljYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fRS5omehb8jpCwVxbBnv0ftfE3KmOLXYtmlUtlsCP_A">

Nice job, Nikhil. 

@sameagen-MW: 
1) Are the line spacings consistent with other sections of the Jenkins build summary?
2) Are the numbers bold in the screenshot above?

**Comment by Vahila** [comment]
The summary is updated as per suggestions.
![image](https://github.com/mathworks/jenkins-matlab-plugin/assets/70003902/57448067-fe54-4461-9d33-70b21edc07a8)
