### ISSUE TITLE
Build report title needs to be updated

### ISSUE THREAD

**Issue by mw-hrastega** [mathworks/jenkins-matlab-plugin#290]
In the interest of consistency, please change the report title from "MATLAB Build Results" to "MATLAB Build Result". In the documentation, we say "result" of a build, not "results" of a build: https://www.mathworks.com/help/matlab/ref/matlab.buildtool.buildresult-class.html.

**Comment by nbhoski** [comment]
Fixed.

**Comment by Vahila** [comment]
Summary is updated as shown below:
![image](https://github.com/mathworks/jenkins-matlab-plugin/assets/70003902/90edb523-3a40-4216-9057-594fa7211f75)
