### ISSUE TITLE
"This build report includes 2 tasks." must be updated.

### ISSUE THREAD

**Issue by mw-hrastega** [mathworks/jenkins-matlab-plugin#291]
"This build report includes 2 tasks." must be updated to something like "This MATLAB build included 2 tasks:"

**Comment by sameagen-MW** [comment]
Maybe we can make the text more concise? Our display stands out as being a bit more verbose in comparison to the others here:

<img width="379" alt="image" src="https://github.com/mathworks/jenkins-matlab-plugin/assets/122639681/a9e67fc8-650f-41b9-a8c8-978fd73b7e89">

For example git doesn't even add a label to the bulleted item.

**Comment by mw-hrastega** [comment]
> Maybe we can make the text more concise? Our display stands out as being a bit more verbose in comparison to the others here:
> 
> <img alt="image" width="379" src="https://private-user-images.githubusercontent.com/122639681/305554532-a9e67fc8-650f-41b9-a8c8-978fd73b7e89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxMTcxMjgsIm5iZiI6MTcwODExNjgyOCwicGF0aCI6Ii8xMjI2Mzk2ODEvMzA1NTU0NTMyLWE5ZTY3ZmM4LTY1MGYtNDFiOS1hOGM4LTk3OGZkNzNiN2U4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNlQyMDUzNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOTIxNTM4ZTgyOTgzZmI5YzgyNTIxYWU1ZmJiZmM2MGQwOTM3NmZkYzk2ODdkN2M5YzZlOGViZTZkODgzYjM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LJ9K9MDZqPXmgJetuz-57Uys7l7j11CVOUaJAnhseAI">
> For example git doesn't even add a label to the bulleted item.

Yes, let's be consistent with others. Also, I don't understand the point of the blue, red, and green colors.

**Comment by nbhoski** [comment]
I have added total task ran:

**Comment by Vahila** [comment]
Message is updated as shown below:
![image](https://github.com/mathworks/jenkins-matlab-plugin/assets/70003902/7e3fc986-7ff2-4490-8b19-e348b627aedc)
