### ISSUE TITLE
Build task result link to the how console log

### ISSUE THREAD

**Issue by adastar** [mathworks/jenkins-matlab-plugin#292]
In the MATLAB Build Results table, when I click the task name link, for example, mtest, it link back to the console output which shows all the output, this is misleading, user may just interests in the build task log. There is no indicator to show user the build task log.

**Comment by sameagen-MW** [comment]
Confirmed. For some further information, It looks like the link that the build report is sending to is 

`http://172.31.79.70:8080/job/yitingw_build_FreeStyleProj/12/console#matlab-mtest]`

while the link element is

`<a id="matlab-mtest" name="matlab-mtest">MATLAB-Build</a>`

Manually removing the `]` does not seem to resolve the issue.

**Comment by nbhoski** [comment]
could not reproduce it on windows is this OS specific? On which OS the Jenkins is installed ?

**Comment by Vahila** [comment]
The links work as expected on Windows with 23b and Jenkins 2.387.2
![image](https://github.com/mathworks/jenkins-matlab-plugin/assets/70003902/121bb35a-6ca0-478c-956d-852f10f8a54c)

**Comment by Vahila** [comment]
In windows also the redirecting link is "http://localhost:8080/job/free_buildvis/16/console#matlab-test]". But I can see the start of the Build log.

One thing to note here is that the Jenkins console log has to be long enough so users can see the start of the MATLAB Build log. If the Jenkins console log isn't bigger than what fits on the screen, it is not possible to scroll up, and user will end up seeing the whole log at once.

**Comment by Vahila** [comment]
The links are working in both Windows and Linux.
