### ISSUE TITLE
Custom build fails due to string issue

### ISSUE THREAD

**Issue by sdobber** [mathworks/jenkins-matlab-plugin#32]
I am trying to set up a new custom build using the Matlab plugin and R2016a on Windows. Even when leaving the "Matlab command" field empty, the build fails when trying to execute 
`"C:\Program Files\MATLAB\R2016a\bin\matlab" -nosplash -nodesktop -noAppIcon -noDisplayDesktop -r 'try,eval(""),catch e,disp(getReport(e,'extended')),exit(1),end,exit' -wait -log`

When running the same command with GUI as
`"C:\Program Files\MATLAB\R2016a\bin\matlab" -r 'try,eval(""),catch e,disp(getReport(e,'extended')),exit(1),end,exit' -wait -log`
Matlab throws an error 
``` 
'try,eval(),catch
Error: String is not terminated properly.
```

**Comment by nbhoski** [comment]
Thanks @sdobber . looking into this

**Comment by nbhoski** [comment]
@sdobber  this is due to the double quotes which we are using in the eval function. double quotes for eval was introduced in R17a onwards and i see you are using R2016a hence the failure. working on to fix this.
