### ISSUE TITLE
No MATLAB bin directory for this machines architecture on mac with apple silicon

### ISSUE THREAD

**Issue by yitingw3** [mathworks/jenkins-matlab-plugin#328]
Got this error on an apple silicon mac agent, same pipeline passed on the Intel mac.

#################### Starting command output ####################
$ ********
Generating MATLAB script with content:
pwd

[mac_free] $ /Users/yitingw/bash/jenkins/workspace/mac_free/.matlab/tempDir.tmp1446622203692712450/run-matlab-command "setenv('MW_ORIG_WORKING_FOLDER', cd('/Users/yitingw/bash/jenkins/workspace/mac_free/.matlab/tempDir.tmp1446622203692712450'));script_rV6jmVQu" -sd matlab
env: /Applications/MATLAB_R2024a.app/bin/maci64/path_per_install: No such file or directory
mkdir: /bin/maci64: Operation not permitted

    matlab: No MATLAB bin directory for this machine architecture.

           ARCH = maci64

exit status 1
Received a nonzero exit code 1 while trying to run MATLAB.
Finished: FAILURE

**Comment by sameagen-MW** [comment]
Fixed in dev_main
