### ISSUE TITLE
Added Simulink Test Reports in Automatic model

### ISSUE THREAD

**Issue by fmacmill** [mathworks/jenkins-matlab-plugin#33]
Thank you for automatic mode - great to have such an easy route to access CI
Would it be possible to add Simulink Test Rpeorts that are generated automatically to the results without having to go to the full custom mode?

**Comment by acampbel** [comment]
@fmacmill This is now done as part of this:

https://github.com/mathworks/jenkins-matlab-plugin/issues/51

This generates "unified" test reports that includes Simulink test information (model information, signals, etc) Please let us know if this is not sufficient for what you are asking for.
