### ISSUE TITLE
Plugin does not work for Apple Silicon Mac agents

### ISSUE THREAD

**Issue by acampbel** [mathworks/jenkins-matlab-plugin#336]
It seems as though we have a hardcoded maci64 in the MATLAB launcher code. Using an Apple Silicon agent violates that assumption.

**Comment by nbhoski** [comment]
Is this same as #328

**Comment by sameagen-MW** [comment]
I think so. Andy can you confirm whether you were using a public release of the plugin and not something that you built from the `dev_main` trunk branch?

**Comment by acampbel** [comment]
Dup of #328
