### ISSUE TITLE
Skipped build tasks do not have a working link

### ISSUE THREAD

**Issue by acampbel** [mathworks/jenkins-matlab-plugin#337]
There is no link for skipped build tasks using the Run MATLAB build step.

**Comment by nbhoski** [comment]
Yes, this was known issue with skip it does not enter into our plugin code hence we currently wont be able to add our sentinel for skip tasks also second rationale was, it would not bemuch helpful to show just skip as there would not be any stack trace or reason to skip will be displayed in the log.

**Comment by mcafaro** [comment]
There is a `skipTask` method on `BuildRunnerPlugin` that is invoked whenever a task will be skipped.
