### ISSUE TITLE
No build result page generated for build steps with buildtool error

### ISSUE THREAD

**Issue by yitingw3** [mathworks/jenkins-matlab-plugin#346]
When I ran a build step which failed due to the error from buildtool, not the task failure. No build result page is generated for that step, should we consider also having the build result page for it?

Here is the build log:
#################### Starting command output ####################
$ ******** ******** ********
Generating MATLAB script with content:
addpath('/Users/yitingw/bash/jenkins/workspace/mac_free@tmp/matlab.tmp3618955174263121762'); buildtool clean mtest

[mac_free] $ /Users/yitingw/bash/jenkins/workspace/mac_free@tmp/matlab.tmp3618955174263121762/run-matlab-command "setenv('MW_ORIG_WORKING_FOLDER', cd('/Users/yitingw/bash/jenkins/workspace/mac_free@tmp/matlab.tmp3618955174263121762'));script_OiD4zjuz" -nojvm
{Error using buildtool (line 25)
Unable to find the file buildfile.m in your current folder or any of its parent
folders. To create a build file in your current folder, execute 'buildtool
-init'.

Error in script_OiD4zjuz (line 2)
addpath('/Users/yitingw/bash/jenkins/workspace/mac_free@tmp/matlab.tmp3618955174263121762'); buildtool clean mtest
} 
exit status 1
Received a nonzero exit code 1 while trying to run MATLAB.
Build step 'Run MATLAB Build' changed build result to FAILURE
Finished: FAILURE

**Comment by nbhoski** [comment]
Hi @yitingw3 we generate results irrespective of task failures. However we do not generate ant result if none of the tasks have run and if there is a failure in buildtool itself.
