### ISSUE TITLE
Skipped and Failed status has link to the logs

### ISSUE THREAD

**Issue by Vahila** [mathworks/jenkins-matlab-plugin#358]
In the MATLAB Build results table, the Skipped and Failed status is hyperlinked to the Jenkins logs. For Succeeded tasks, the status is only a text with no links.

Should the links to logs be accessible through Status and tasks? or only through Tasks?

**Comment by mw-kapilg** [comment]
It is the expected behavior as people are usually more interested in logs for case of Failed/Skipped tasks in their build. They can still use the task name hyperlink to navigate to logs of successful tasks
