### ISSUE TITLE
Unclear message shown in logs when using MPM install

### ISSUE THREAD

**Issue by Vahila** [mathworks/jenkins-matlab-plugin#369]
Whenusing MPM to install MATLAB, there is an unclear message "**The path which is trying to uppend is **/mathworks/devel/sandbox/vkayithi/jenkinsAgent/tools/com.mathworks.ci.MatlabInstallation/22b/R2022bU7/bin/matlab
"  in the logs.

![image](https://github.com/user-attachments/assets/9b89940b-93a0-49ac-877a-7554e0e14e9c)

The wording of the message is a bit confusing.

**Comment by nbhoski** [comment]
Fixed
