### ISSUE TITLE
-noAppIcon option not available until 15b

### ISSUE THREAD

**Issue by mcafaro** [mathworks/jenkins-matlab-plugin#41]
The -noAppIcon option was introduced in 15b, so I think the use of this option will need a version check.

https://github.com/mathworks/jenkins-matlab-plugin/blob/e824674a8f3a5a106ecfcdbad815b69467ebb37d/src/main/java/com/mathworks/ci/MatlabBuilder.java#L477

**Comment by nbhoski** [comment]
I verified it on previous MATLAB versions , it seems that the previous version just ignores the startup options which are not supported with a warning but it does not affect executing MATLAB command. should this be a bug still?

**Comment by mcafaro** [comment]
I'd say it's still a bug, especially if the warning is visible to the user. We generally fail tests on unexpected warnings.

**Comment by nbhoski** [comment]
noAppIcon is also not documented.and is also not much of value add. I guess removing it from the startup option would be good idea. any suggestions otherwise?
