### ISSUE TITLE
Use of double quotes not available until 17a

### ISSUE THREAD

**Issue by mcafaro** [mathworks/jenkins-matlab-plugin#42]
The ability to create a string using double quotes was introduced in 17a, so I think the use of double quotes in this line should be switched to single quotes and properly escaped.

https://github.com/mathworks/jenkins-matlab-plugin/blob/e824674a8f3a5a106ecfcdbad815b69467ebb37d/src/main/java/com/mathworks/ci/MatlabBuilder.java#L498

**Comment by nbhoski** [comment]
#32  seems to be the same issue.
