### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by mw-hrastega** [mathworks/jenkins-matlab-plugin#50]

**Comment by acampbel** [comment]
What is this issue?

**Comment by mw-hrastega** [comment]
I created this issue to generate URLs for the screenshots and embed them in the example.

**Comment by nbhoski** [comment]
This issue was to replace screenshots. i think its already done . @mw-hrastega  should we close this

**Comment by mw-hrastega** [comment]
I am not sure, Nikhil. Aren't we expected to update the screenshots soon (adding folder paths)?

**Comment by nbhoski** [comment]
Yes, But this issue was raise for older images which had mouse pointer on it i guess which is already addressed .

**Comment by mw-hrastega** [comment]
Thanks for the information, Nikhil. Yes, the issue can be closed.
