### ISSUE TITLE
Option to filter test files or define root folder to search test files in automatic mode

### ISSUE THREAD

**Issue by pablorcum** [mathworks/jenkins-matlab-plugin#54]
As far as I know, automatic mode runs all the test files located in a project. However, I usually have two or more different test files for different purposes (demo, complete tests, regression tests, etc). I use a custom script to run in Jenkins only those tests located in a certain "regression_tests" folder, because I don't want to run everything.

It will be very helpful to filter which test files we want to run either using label filtering or defining the path to start searching for test files.

**Comment by acampbel** [comment]
HI @pablorcum, What version of MATLAB are you using? Are you leveraging [Projects](https://www.mathworks.com/help/matlab/projects.html) (used to be Simulink Projects)?

**Comment by nbhoski** [comment]
Completed.
