### ISSUE TITLE
Pipeline support.

### ISSUE THREAD

**Issue by dapperfu** [mathworks/jenkins-matlab-plugin#57]
I see Pipeline support is 'todo'. Is there an estimation on that? Keeping the build process as part of the version controlled system is a great feature. It also makes it easy to tie pipeline code to requirements documents.

**Comment by nbhoski** [comment]
Thanks for reaching out @jed-frey . We are actively working on pipeline support and it is one of the important features that we are currently working on. We are hoping to have it release at the earliest.

**Comment by dapperfu** [comment]
If anyone is looking to use a Pipeline anytime soon here are some examples that I put together demonstrating how to use a Jenkinsfile to generate code for Ardunio hardware:

https://github.com/AutomotiveDevOps/ArduinoHardware

It is currently tested on Ubuntu/R2019b. I also have it working internally with Docker to add proper DevOps to our Simulink Embedded Coder development pipeline.

**Comment by nbhoski** [comment]
Thanks @dapperfu  Pipeline support is released and you could use runMATLABCommand step to invoke the script files.

**Comment by nbhoski** [comment]
Release #116  supports Pipeline hence closing this issue.
