### ISSUE TITLE
Remove "Unable to find MATLAB" warnings

### ISSUE THREAD

**Issue by mcafaro** [mathworks/jenkins-matlab-plugin#83]
Now that the plugin just calls whatever `matlab` command it finds on the system path, we should remove the "Unable to find MATLAB" warnings when you select to produce a test artifact.

<img width="874" alt="Screen Shot 2020-04-01 at 8 55 28 AM" src="https://user-images.githubusercontent.com/34887852/78139470-8e9ca100-73f6-11ea-8029-7ea4064d87cb.png">

**Comment by nbhoski** [comment]
Removed all UI valdation is PR #86

**Comment by nbhoski** [comment]
Done .
