### ISSUE TITLE
Need to add more unit tests

### ISSUE THREAD

**Issue by acampbel** [mathworks/jenkins-matlab-plugin#9]
Code coverage metrics demonstrate some holes in coverage.

**Comment by nbhoski** [comment]
Added few tests to increase the code coverage. code coverage from 71% has reached to 92% after these changes. 

https://dev.azure.com/iat-ci/jenkins-matlab-plugin/_build/results?buildId=83&view=codecoverage-tab

**Comment by nbhoski** [comment]
added unit tests to increase the earlier code coverage from 71 % to 93% . there is scope of still increasing it if we get to test it against actual MATLAB instance and could cover more functional tests which are dependent on actual MATLAB instance . I will close this issue for now .
