### ISSUE TITLE
PDF Test Report not supported on Mac. Text Input Help on PDF Report could have it as warning/error message

### ISSUE THREAD

**Issue by SangaviJayagopi** [mathworks/jenkins-matlab-plugin#93]

**Comment by abhargav-mw** [comment]
Hi Sangavi,

As of v2.1.1, the help text for PDF Test Report Generation shows a Note stating This feature is not currently supported on Mac Platforms.

![PDFReportMac](https://user-images.githubusercontent.com/68549146/88538797-97f8eb80-d02d-11ea-8961-f4acffc43b6f.png)

Does this suffice or should we bring it to UI as a Warning (Above File Path)?

**Comment by SangaviJayagopi** [comment]
@abhargav-mw  I was looking at enhancement from the point where the checkbox and text input for PDF in case of Mac could not show up. But, I guess the way of determining the OS during run time or compile time of the plugin would be beyond scope. Correct me if I am wrong. 

Having said that, the note we have would suffice.

**Comment by abhargav-mw** [comment]
Marking this issue as closed. Going forward in R2020b release, this limitation for PDF Report  generation should be fixed.
