### ISSUE TITLE
/taptest results.tap text input fails in Mac

### ISSUE THREAD

**Issue by SangaviJayagopi** [mathworks/jenkins-matlab-plugin#94]

**Comment by SangaviJayagopi** [comment]
Started by user Sangavi Jayagopi
Running as SYSTEM
Building on master in workspace /Users/sjayagop/.jenkins/workspace/test_text_input
[test_text_input] $ /var/folders/bc/l10_249126g1thr9hhsv2wj4000fnq/T//02fa1899-4271-4ac0-bceb-858d533b1e36/run_matlab_command.sh exit(runMatlabTests('TAPResultsPath','/taptestresults.tap'))
{Error using fclose
Invalid file identifier. Use fopen to generate a valid file identifier.

Error in runMatlabTests>getTapResultFile (line 145)
fclose(fopen(resultsDir,'w'));

Error in runMatlabTests (line 64)
        tapFile = getTapResultFile(tapReportPath);
} 
Build step 'Run MATLAB Tests' changed build result to FAILURE
Finished: FAILURE

**Comment by nbhoski** [comment]
does it work for other artifact and on mac and all artifacts on other platform ?

**Comment by SangaviJayagopi** [comment]
**Mac:**
The same problem occurs with other Artifacts too. Here is the log when I tried with Junit and Tap:
Started by user Sangavi Jayagopi
Running as SYSTEM
Building on master in workspace /Users/sjayagop/.jenkins/workspace/test_text_input
[test_text_input] $ /var/folders/bc/l10_249126g1thr9hhsv2wj4000fnq/T//31a2622f-b91e-475c-a129-4a1f56f42752/run_matlab_command.sh exit(runMatlabTests('JUnitResultsPath','/matlabTestArtifacts.xml','TAPResultsPath','/taptestresults.tap'))
{Error using fclose
Invalid file identifier. Use fopen to generate a valid file identifier.

Error in runMatlabTests>getTapResultFile (line 145)
fclose(fopen(resultsDir,'w'));

Error in runMatlabTests (line 64)
        tapFile = getTapResultFile(tapReportPath);
} 
Build step 'Run MATLAB Tests' changed build result to FAILURE
Finished: FAILURE


**Windows Platform:**
Interestingly, when I give file path as: \taptestresults.tap and for Junit as:\matlabTestArtifacts.xml . Artifacts dont get generated and also there is no build failure.

**Comment by nbhoski** [comment]
In either case we do not support absolute path for test artifacts . test artifact path should be relative to the workspace where name after / or \ should be folder name followed by file name. what you are trying is not valid relative path format you could try /somepath/filename.xml which will create a folder named somepath in workspace and inside that the specified file will be generated.
