### ISSUE TITLE
When same name for artifacts as Text Input 'TestArtifacts' for Junit and Tap. Only Junit is produced.Any warning/help message to not have same names?

### ISSUE THREAD

**Issue by SangaviJayagopi** [mathworks/jenkins-matlab-plugin#95]

**Comment by nbhoski** [comment]
@SangaviJayagopi Can you provide more info or reproducing steps would help.

**Comment by SangaviJayagopi** [comment]
1. Go to the Jenkins Configure page -> Add Build Step -> Run MATLAB Tests -> Check Artifacts 'Junit-style Test Reports' and 'TapTestResults'
2. Give these inputs in the respective field Junit File path: 'TestArtifacts' and TAP Test Results: 'TestArtifacts'
3.After the build is run, the workspace has only one report 'TestArtifacts' which is Junit Style

Potentially, adding .tap and .xml would solve the issue. But, what if users dont add the extension?

**Comment by nbhoski** [comment]
I guess its native OS behavior that it does not allow files with the same name unless you provide the extensions or unless they are not in same location.

**Comment by SangaviJayagopi** [comment]
I am closing this issue taking the fact if the customers find a similar issue, we will advice them to add extensions in the file names.
