### ISSUE TITLE
Empty/Blank Text Input does not warning message. Artifact not generated

### ISSUE THREAD

**Issue by SangaviJayagopi** [mathworks/jenkins-matlab-plugin#96]

**Comment by nbhoski** [comment]
@SangaviJayagopi  ths was decided that we will remove all the warning message from UI and instead show it on the console log. the reason being now we invoke MATLAB directly and if user already has MATLAB in PATH then we would not be able to validate the warning against it.

**Comment by SangaviJayagopi** [comment]
This is not for the MATLAB Root Text Input. The issue is about blank Text Input for the 'File Path'.
When the Artifact is checked and when there is Blank File path, no artifact is generated in the workspace at the end of build. There should be a warning which does not let the user have blank text input for the File Path.

**Comment by nbhoski** [comment]
i feel this is expected behavior not to generate anything when file path is not provided . We auto populate the default and we allow blank text box as we cannot restrict user not to have blank  and run the job .

**Comment by SangaviJayagopi** [comment]
Assuming, specifying file path is not mandatory, when the check box is checked , why dont we generate artifacts in a default location? 
In the case where the user does not want the artifact, he should not be checking the box.

Take this case:
1. The user checks the TAP Result check box
2.Decides to edit the default file path name
3.Clears the field completely and leaves it blank without adding new name
4.The user after the build would expect artifact in the default location if no name is specified.

**Comment by nbhoski** [comment]
Fix is merged  #101

**Comment by SangaviJayagopi** [comment]
Help text updated to have appropriate message.

Verified and completed.
